# Generated by Django 6.0 on 2026-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('delivery_address', models.TextField()),
                ('phone_brand', models.CharField(max_length=50)),
                ('phone_model', models.CharField(max_length=50)),
                ('phone_size', models.CharField(blank=True, max_length=20, null=True)),
                ('case_color', models.CharField(max_length=30)),
                ('protection_level', models.CharField(choices=[('Normal', 'Normal'), ('Heavy', 'Heavy'), ('Extreme', 'Extreme')], default='Normal', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
